### ISSUE TITLE
consult-async-default-split is deprecated

### ISSUE THREAD

**Issue by minad** [gagbo/consult-lsp#11]
See https://github.com/minad/consult/blob/6ce9aa58e74da92e391cfe938bc3da4f47ab591e/consult.el#L3610

**Comment by gagbo** [comment]
If I don’t want to give an initial argument I need the default-split. I tried to look into

https://github.com/minad/consult/blob/6ce9aa58e74da92e391cfe938bc3da4f47ab591e/consult.el#L1328-1331

but it looks like only 1 of the default values has an ":initial" key

https://github.com/minad/consult/blob/6ce9aa58e74da92e391cfe938bc3da4f47ab591e/consult.el#L123-L129

So does that mean I should go `(or (plist-get (consult--async-split-style) :initial) "")` ?

**Comment by minad** [comment]
> So does that mean I should go (or (plist-get (consult--async-split-style) :initial) "") ?

Yes, or use `(consult--async-split-initial "")`.

**Comment by gagbo** [comment]
I'll set `initial` in a let binding later, so that if eventually I want to change that later it's going to be easier. Thanks for the help
