### ISSUE TITLE
Preview overlays stick around when quitting from consult-lsp-diagnostics

### ISSUE THREAD

**Issue by hugonobrega** [gagbo/consult-lsp#19]
The `consult-preview-line` and `consult-preview-cursor` overlays stick around when quitting `C-g` out of `consult-lsp-diagnostics`

Steps to reproduce:
1) Have a file with at least 1 diagnosed error/warning by the corresponding lsp-server, like in python
```python
def f(x):
    Pass
```
2) Call `M-x consult-lsp-diagnostics` and cycle through some candidates
3) Hit `C-g` and the last preview overlays stick around

Tested on (recent) emacs 28, consult-lsp 8ed43c6eaaf3

**Comment by gagbo** [comment]
It's probably around 

https://github.com/gagbo/consult-lsp/blob/8ed43c6eaaf3ff8963861fa3234e81683be91e45/consult-lsp.el#L245-L246

But I'll need to review the code in consult as well to be sure

**Comment by hugonobrega** [comment]
I think the main problem was the missing `(funcall jump nil t)` but I'm *pretty sure* I also saw problems with the conditions in the two `when` calls, so I refactored into a `cond` which should avoid it
