### ISSUE TITLE
consult-lsp-file-symbols duplicate with consult-imenu

### ISSUE THREAD

**Issue by shaqxu** [gagbo/consult-lsp#28]
I think consult-lsp-file-symbols is not required

**Comment by gagbo** [comment]
We discussed this a bit in [this issue](https://github.com/gagbo/consult-lsp/issues/23) and the PR linked in the first comment. It kind of does the same thing, but also allows the optional grouping now, and anyway it's not too big of a function now, so I'm okay with leaving `file-symbols` here for now. If it ever becomes a maintenance burden I'll probably remove it somehow.
