### ISSUE TITLE
"consult--position-marker" has renamed

### ISSUE THREAD

**Issue by vpxyz** [gagbo/consult-lsp#36]
Hi, 
3 days ago minad renamed consult--position-marker to consult--marker-from-line-column, in melpa's 'consult' package. This refactoring broke consult-lsp. 
Perhaps it would be better to put a copy in consult-lsp? This function is simple and has no dependency on consult functions.
Thank you.

**Comment by gagbo** [comment]
Thanks for the heads up, I tried to make a change in 37169e2695570aedc26431ca649ed2f0ab62ec1a 

Please reopen the issue if that still fails to work for you!
