### ISSUE TITLE
consult--read: :title argument has been replaced by :group argument

### ISSUE THREAD

**Issue by minad** [gagbo/consult-lsp#4]
See here https://github.com/minad/consult/commit/d693b25031ca52e254d6c03f78ce44d04615aa5e

**Comment by minad** [comment]
Hey @gagbo, thank you for fixing this! It could happen that you have to revert the commit again at some point, since I am currently discussing with the Emacs developers about how the grouping/title API could be integrated into Emacs completing-read itself. I am sorry for the back and forth. I will ping you again as soon as the situation has settled.

**Comment by gagbo** [comment]
It's okay don't worry. If possible it'd be great to tag the branch, this way if people want to use MELPA stable or stuff I can properly point to the correct consult version in the Package-Requires in the header !

**Comment by minad** [comment]
Yes, this is going to be 0.7 then, which will be released in a while.

**Comment by minad** [comment]
But actually, you can just revert that commit and use :title again and everything should work with 0.6 and the not-yet-released 0.7. The short switch to :group turned out to be a mistake :shrug:

**Comment by gagbo** [comment]
I'll just close the PR then. Sorry for not answering cleanly before (and thank you for telling me about the change), but in order to not forget about it I created a small PR with the intent to look over it during the weekend. So if you reverted the change I'll just close the PR during the weekend instead of merging it :)

**Comment by minad** [comment]
Please pull this now. I finally renamed the keyword argument to match the Emacs 28 group-function. Thanks!
